//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Hired_for_Position
{
	public virtual object Posting_ID
	{
		get;
		set;
	}

	public virtual object Applicant_CPnum
	{
		get;
		set;
	}

	public virtual object Position_ID
	{
		get;
		set;
	}

	public virtual object Hired_Date
	{
		get;
		set;
	}

	public virtual void Confirm_Hire()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Revoke_Hired()
	{
		throw new System.NotImplementedException();
	}

}

