//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Request_New_Position
{
	public virtual object Position_Title
	{
		get;
		set;
	}

	public virtual object Position_School
	{
		get;
		set;
	}

	public virtual object Position_Start_Date
	{
		get;
		set;
	}

	public virtual object Position_End_date
	{
		get;
		set;
	}

	public virtual object Position_Qualification
	{
		get;
		set;
	}

	public virtual object Position_Description
	{
		get;
		set;
	}

	public virtual object Position_FTE
	{
		get;
		set;
	}

	public virtual object Position_ID
	{
		get;
		set;
	}

	public virtual object Position_Contact_staff
	{
		get;
		set;
	}

	

	public virtual void add()
	{
		throw new System.NotImplementedException();
	}

	public virtual void delete()
	{
		throw new System.NotImplementedException();
	}

	public virtual void edit()
	{
		throw new System.NotImplementedException();
	}

	public virtual void sent_request()
	{
		throw new System.NotImplementedException();
	}

}

