'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports Microsoft.VisualStudio.TestTools.WebTesting
Imports Microsoft.VisualStudio.TestTools.WebTesting.Rules
Imports System
Imports System.Collections.Generic
Imports System.Text

Namespace Web_Performance_Test___LTO_List

    Public Class WebTest_selectInterviewCoded
        Inherits ThreadedWebTest

        Public Sub New()
            MyBase.New()
            Me.PreAuthenticate = True
            Me.Proxy = "default"
        End Sub

        Public Overrides Sub Run()
            'Initialize validation rules that apply to all requests in the WebTest
            If (Me.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low) Then
                Dim validationRule1 As ValidateResponseUrl = New ValidateResponseUrl()
                AddHandler ValidateResponse, AddressOf validationRule1.Validate
            End If
            If (Me.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low) Then
                Dim validationRule2 As ValidationRuleResponseTimeGoal = New ValidationRuleResponseTimeGoal()
                validationRule2.Tolerance = 0.0R
                AddHandler ValidateResponseOnPageComplete, AddressOf validationRule2.Validate
            End If

            Dim request1 As WebTestRequest = New WebTestRequest("https://webt01.tcdsb.org:8443/test/lto")
            request1.ThinkTime = 4
            request1.ExpectedResponseUrl = "https://webt01.tcdsb.org:8443/TEST/LTO/logon.aspx?ReturnUrl=%2ftest%2flto"
            Dim extractionRule1 As ExtractHiddenFields = New ExtractHiddenFields()
            extractionRule1.Required = True
            extractionRule1.HtmlDecode = True
            extractionRule1.ContextParameterName = "1"
            AddHandler request1.ExtractValues, AddressOf extractionRule1.Extract
            MyBase.Send(request1)
            request1 = Nothing

            Dim request2 As WebTestRequest = New WebTestRequest("https://webt01.tcdsb.org:8443/TEST/LTO/logon.aspx")
            request2.Method = "POST"
            request2.ExpectedResponseUrl = "https://webt01.tcdsb.org:8443/test/lto/"
            request2.Headers.Add(New WebTestRequestHeader("Referer", "https://webt01.tcdsb.org:8443/TEST/LTO/logon.aspx?ReturnUrl=%2ftest%2flto"))
            request2.QueryStringParameters.Add("ReturnUrl", "%2ftest%2flto", False, False)
            Dim request2Body As FormPostHttpBody = New FormPostHttpBody()
            request2Body.FormPostParameters.Add("__EVENTTARGET", Me.Context("$HIDDEN1.__EVENTTARGET").ToString)
            request2Body.FormPostParameters.Add("__EVENTARGUMENT", Me.Context("$HIDDEN1.__EVENTARGUMENT").ToString)
            request2Body.FormPostParameters.Add("__VIEWSTATE", Me.Context("$HIDDEN1.__VIEWSTATE").ToString)
            request2Body.FormPostParameters.Add("__VIEWSTATEGENERATOR", Me.Context("$HIDDEN1.__VIEWSTATEGENERATOR").ToString)
            request2Body.FormPostParameters.Add("__EVENTVALIDATION", Me.Context("$HIDDEN1.__EVENTVALIDATION").ToString)
            request2Body.FormPostParameters.Add("txtDomain", "CEC")
            request2Body.FormPostParameters.Add("txtUsername", "mif")
            request2Body.FormPostParameters.Add("txtPassword", "")
            request2Body.FormPostParameters.Add("btnLogin", "Login")
            request2Body.FormPostParameters.Add("txtResolution", "1680x1050")
            request2.Body = request2Body
            MyBase.Send(request2)
            request2 = Nothing

            Dim request3 As WebTestRequest = New WebTestRequest("https://webt01.tcdsb.org:8443/test/lto/LTOHRStaffs/Loading.aspx")
            request3.Headers.Add(New WebTestRequestHeader("Referer", "https://webt01.tcdsb.org:8443/test/lto/"))
            request3.QueryStringParameters.Add("pID", "0", False, False)
            MyBase.Send(request3)
            request3 = Nothing

            Dim request4 As WebTestRequest = New WebTestRequest("https://webt01.tcdsb.org:8443/test/lto/LTOHRStaffs/WelcomePage.aspx")
            request4.ThinkTime = 1
            request4.Headers.Add(New WebTestRequestHeader("Referer", "https://webt01.tcdsb.org:8443/test/lto/"))
            MyBase.Send(request4)
            request4 = Nothing

            Dim request5 As WebTestRequest = New WebTestRequest("https://webt01.tcdsb.org:8443/test/lto/LTOHRStaffs/Loading.aspx")
            request5.Headers.Add(New WebTestRequestHeader("Referer", "https://webt01.tcdsb.org:8443/test/lto/"))
            request5.QueryStringParameters.Add("pID", "4", False, False)
            MyBase.Send(request5)
            request5 = Nothing

            Dim request6 As WebTestRequest = New WebTestRequest("https://webt01.tcdsb.org:8443/test/lto/LTOHRStaffs/PublishedList.aspx")
            request6.ThinkTime = 3
            request6.Headers.Add(New WebTestRequestHeader("Referer", "https://webt01.tcdsb.org:8443/test/lto/"))
            request6.QueryStringParameters.Add("sID", "InterviewApplicant", False, False)
            MyBase.Send(request6)
            request6 = Nothing

            Dim request7 As WebTestRequest = New WebTestRequest("https://webt01.tcdsb.org:8443/test/lto/LTOHRStaffs/PublishedList.aspx")
            request7.ExpectedResponseUrl = "https://webt01.tcdsb.org:8443/test/lto/LTOHRStaffs/PublishedList.aspx?sID=Intervi" & _
                "ewApplicant#"
            request7.QueryStringParameters.Add("sID", "InterviewApplicant", False, False)
            MyBase.Send(request7)
            request7 = Nothing

            Dim request8 As WebTestRequest = New WebTestRequest("https://webt01.tcdsb.org:8443/test/lto/LTOHRStaffs/Loading.aspx")
            request8.ExpectedResponseUrl = "https://webt01.tcdsb.org:8443/test/lto/LTOHRStaffs/Loading.aspx?pID=2&SchoolYear=" & _
                "20152016&SchoolCode=0519&PositionID=3903&SchoolName=Blessed Cardinal Newman Cath" & _
                "olic Secondary School"
            request8.QueryStringParameters.Add("pID", "2", False, False)
            request8.QueryStringParameters.Add("SchoolYear", "20152016", False, False)
            request8.QueryStringParameters.Add("SchoolCode", "0519", False, False)
            request8.QueryStringParameters.Add("PositionID", "3903", False, False)
            request8.QueryStringParameters.Add("SchoolName", "Blessed%20Cardinal%20Newman%20Catholic%20Secondary%20School", False, False)
            MyBase.Send(request8)
            request8 = Nothing

            Dim request9 As WebTestRequest = New WebTestRequest("https://webt01.tcdsb.org:8443/test/lto/LTOHRStaffs/Loading.aspx")
            request9.Headers.Add(New WebTestRequestHeader("Referer", "https://webt01.tcdsb.org:8443/test/lto/LTOHRStaffs/PublishedList.aspx?sID=Intervi" & _
                        "ewApplicant"))
            request9.QueryStringParameters.Add("pID", "2", False, False)
            request9.QueryStringParameters.Add("SchoolYear", "20152016", False, False)
            request9.QueryStringParameters.Add("SchoolCode", "0519", False, False)
            request9.QueryStringParameters.Add("PositionID", "3903", False, False)
            request9.QueryStringParameters.Add("SchoolName", "Blessed+Cardinal+Newman+Catholic+Secondary+School", False, False)
            MyBase.Send(request9)
            request9 = Nothing

            Dim request10 As WebTestRequest = New WebTestRequest("https://webt01.tcdsb.org:8443/test/lto/LTOHRStaffs/ApplicantList.aspx")
            request10.ExpectedResponseUrl = "https://webt01.tcdsb.org:8443/test/lto/LTOHRStaffs/ApplicantList.aspx?SchoolYear=" & _
                "20152016&SchoolCode=0519&SchoolName=Blessed Cardinal Newman Catholic Secondary S" & _
                "chool&PositionID=3903&includAll="
            request10.QueryStringParameters.Add("SchoolYear", "20152016", False, False)
            request10.QueryStringParameters.Add("SchoolCode", "0519", False, False)
            request10.QueryStringParameters.Add("SchoolName", "Blessed%20Cardinal%20Newman%20Catholic%20Secondary%20School", False, False)
            request10.QueryStringParameters.Add("PositionID", "3903", False, False)
            request10.QueryStringParameters.Add("includAll", "", False, False)
            MyBase.Send(request10)
            request10 = Nothing

            Dim request11 As WebTestRequest = New WebTestRequest("https://webt01.tcdsb.org:8443/test/lto/LTOHRStaffs/ApplicantList.aspx")
            request11.ThinkTime = 5
            request11.Headers.Add(New WebTestRequestHeader("Referer", "https://webt01.tcdsb.org:8443/test/lto/LTOHRStaffs/PublishedList.aspx?sID=Intervi" & _
                        "ewApplicant"))
            request11.QueryStringParameters.Add("SchoolYear", "20152016", False, False)
            request11.QueryStringParameters.Add("SchoolCode", "0519", False, False)
            request11.QueryStringParameters.Add("SchoolName", "Blessed+Cardinal+Newman+Catholic+Secondary+School", False, False)
            request11.QueryStringParameters.Add("PositionID", "3903", False, False)
            request11.QueryStringParameters.Add("includAll", "", False, False)
            MyBase.Send(request11)
            request11 = Nothing

            Dim request12 As WebTestRequest = New WebTestRequest("https://webt01.tcdsb.org:8443/test/lto/Loading2.aspx")
            request12.ExpectedResponseUrl = "https://webt01.tcdsb.org:8443/test/lto/Loading2.aspx?pID=LTOHRStaffs/NoticeToPrin" & _
                "cipal.aspx&SchoolYear=20152016&SchoolCode=0519&PositionID=3903&SchoolName=Blesse" & _
                "d Cardinal Newman Catholic Secondary School"
            request12.QueryStringParameters.Add("pID", "LTOHRStaffs/NoticeToPrincipal.aspx", False, False)
            request12.QueryStringParameters.Add("SchoolYear", "20152016", False, False)
            request12.QueryStringParameters.Add("SchoolCode", "0519", False, False)
            request12.QueryStringParameters.Add("PositionID", "3903", False, False)
            request12.QueryStringParameters.Add("SchoolName", "Blessed%20Cardinal%20Newman%20Catholic%20Secondary%20School", False, False)
            MyBase.Send(request12)
            request12 = Nothing

            Dim request13 As WebTestRequest = New WebTestRequest("https://webt01.tcdsb.org:8443/test/lto/Loading2.aspx")
            request13.Headers.Add(New WebTestRequestHeader("Referer", "https://webt01.tcdsb.org:8443/test/lto/"))
            request13.QueryStringParameters.Add("pID", "LTOHRStaffs/NoticeToPrincipal.aspx", False, False)
            request13.QueryStringParameters.Add("SchoolYear", "20152016", False, False)
            request13.QueryStringParameters.Add("SchoolCode", "0519", False, False)
            request13.QueryStringParameters.Add("PositionID", "3903", False, False)
            request13.QueryStringParameters.Add("SchoolName", "Blessed+Cardinal+Newman+Catholic+Secondary+School", False, False)
            MyBase.Send(request13)
            request13 = Nothing

            Dim request14 As WebTestRequest = New WebTestRequest("https://webt01.tcdsb.org:8443/test/lto/LTOHRStaffs/NoticeToPrincipal.aspx")
            request14.ExpectedResponseUrl = "https://webt01.tcdsb.org:8443/test/lto/LTOHRStaffs/NoticeToPrincipal.aspx?SchoolY" & _
                "ear=20152016&Schoolcode=0519&PositionID=3903&SchoolName=Blessed Cardinal Newman " & _
                "Catholic Secondary School"
            request14.QueryStringParameters.Add("SchoolYear", "20152016", False, False)
            request14.QueryStringParameters.Add("Schoolcode", "0519", False, False)
            request14.QueryStringParameters.Add("PositionID", "3903", False, False)
            request14.QueryStringParameters.Add("SchoolName", "Blessed%20Cardinal%20Newman%20Catholic%20Secondary%20School", False, False)
            MyBase.Send(request14)
            request14 = Nothing

            Dim request15 As WebTestRequest = New WebTestRequest("https://webt01.tcdsb.org:8443/test/lto/LTOHRStaffs/NoticeToPrincipal.aspx")
            request15.ThinkTime = 2
            request15.Headers.Add(New WebTestRequestHeader("Referer", "https://webt01.tcdsb.org:8443/test/lto/"))
            request15.QueryStringParameters.Add("SchoolYear", "20152016", False, False)
            request15.QueryStringParameters.Add("Schoolcode", "0519", False, False)
            request15.QueryStringParameters.Add("PositionID", "3903", False, False)
            request15.QueryStringParameters.Add("SchoolName", "Blessed+Cardinal+Newman+Catholic+Secondary+School", False, False)
            MyBase.Send(request15)
            request15 = Nothing

            Dim request16 As WebTestRequest = New WebTestRequest("https://webt01.tcdsb.org:8443/test/lto/")
            request16.ThinkTime = 3
            request16.ExpectedResponseUrl = "https://webt01.tcdsb.org:8443/test/lto/#"
            MyBase.Send(request16)
            request16 = Nothing

            Dim request17 As WebTestRequest = New WebTestRequest("https://webt01.tcdsb.org:8443/test/lto/Loading2.aspx")
            request17.Headers.Add(New WebTestRequestHeader("Referer", "https://webt01.tcdsb.org:8443/test/lto/"))
            request17.QueryStringParameters.Add("pID", "LTOHRStaffs/ApplicantDetails.aspx", False, False)
            request17.QueryStringParameters.Add("SchoolYear", "20152016", False, False)
            request17.QueryStringParameters.Add("ApplyUserID", "00027344", False, False)
            request17.QueryStringParameters.Add("PositionID", "3903", False, False)
            request17.QueryStringParameters.Add("TeacherName", "", False, False)
            MyBase.Send(request17)
            request17 = Nothing

            Dim request18 As WebTestRequest = New WebTestRequest("https://webt01.tcdsb.org:8443/test/lto/LTOHRStaffs/ApplicantDetails.aspx")
            request18.Headers.Add(New WebTestRequestHeader("Referer", "https://webt01.tcdsb.org:8443/test/lto/"))
            request18.QueryStringParameters.Add("SchoolYear", "20152016", False, False)
            request18.QueryStringParameters.Add("ApplyUserID", "00027344", False, False)
            request18.QueryStringParameters.Add("PositionID", "3903", False, False)
            request18.QueryStringParameters.Add("TeacherName", "", False, False)
            MyBase.Send(request18)
            request18 = Nothing
        End Sub
    End Class
End Namespace
